name: Daily Coding Tip Bot

on:
  schedule:
    - cron: '0 5 * * *'    # Runs at 10:30 AM IST every day (5:00 AM UTC)
  workflow_dispatch:        # Allows manual run

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install tweepy

    - name: Run tweet bot
      run: python tweet_bot.py
